### ISSUE TITLE
MobX deserves a bit more

### ISSUE THREAD

**Issue by danielkcz** [adam-golab/react-developer-roadmap#68]
Since you list such a bunch of other packages for React, why not to add also [mobx-react](https://github.com/mobxjs/mobx-react), [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite), [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree)? These are all important parts of the ecosystem.

**Comment by adam-golab** [comment]
Hi @FredyC,
I'm not convinced to adding first two libraries. I mentioned `redux` but it's obvious that it requires `react-redux`. So that's why I'm quite against adding `mobx-react` and `mobx-react-lite` as they are bindings to `mobx` which is already included in the roadmap. Please correct me if I'm wrong regarding those libraries. Maybe they are doing something more.
Regarding `mobx-state-tree`, I didn't use it, so that's why it's missing on the roadmap. At first sight, it looks very nice, so I think it's worth to add it. I'll do it in my free time.

**Comment by HertzaHaeon** [comment]
IMHO, MobX should be a valid first choice of state management library. It's functional and mature enough, and for beginners it's arguable easier to pick up than all the boiler plate and concepts of Redux.

But there's also [more to state management than MobX and Redux](https://dev.to/joshua/the-state-of-the-state-react-state-management-in-2018-2l0c).
